### ISSUE TITLE
Erroneous sample classes

### ISSUE THREAD

**Issue by klevan** [BioKIC/NEON-Biorepo-Collections#12]
Erroneous sample classes for externally held samples that were collected by NEON staff.

Revised classes are below.

institutioncode | collectioncode|neonsampleclass
-- | -- | --
CMNH | INV | bet_IDandpinning_in.individualID
EMEC | EMEC | bet_IDandpinning_in.individualID
MSB | MAMM | mam_pertrapnight_in.bloodSampleID, mam_pertrapnight_in.earSampleID, mam_pertrapnight_in.fecalSampleID, mam_pertrapnight_in.hairSampleID, mam_pertrapnight_in.voucherSampleID
NEON | SOIC-MP | mgp_perarchivesample_in.archiveID
UMICH | SOIC | spc_perbulksample_in.bulkDensIDnrcs

**Comment by arbolitoloco** [comment]
I've updated these `sampleClass` entries accordingly in the database, and temporarily "turned off" for automatic sample harvesting.
Just for future reference, collection `UMICH/SOIC` had the following information in our database:

institutioncode | collectioncode | neonsampleclass
-----------------|------------------|-------------------
UMBS | SAFE | spc_perbiogeosample_in.biogeoIDnrcs
